name: Update research page

on:
  push:
    paths:
      - "_data/research-input.yml"
  pull_request:
    paths:
      - "_data/research-input.yml"
  pull_request_target:
    paths:
      - "_data/research-input.yml"

jobs:
  update_research:
    name: Update Manubot-generated citations on research page
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install manubot
        run: pip install --upgrade manubot
      - name: Build updated research output file
        run: python _data/build-research.py
      - name: Commit new research output file
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: "_data/research-output.yml"
          commit_message: "Update Manubot-generated citations on research page"
